language: node_js
cache: yarn
before_install:
- sudo apt-get install -y graphicsmagick

node_js:
  - "node"
  - "lts/*"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
      - yarn run test:coveralls
